### PR TITLE
fix processUncompressedBlock

### PR DESCRIPTION
**Pull request by hnhhzy**

### CODE REVIEW

**Comment by 4as** [comment]
Could you explain why are proposing this change?

**Comment by hnhhzy** [comment]
has bug

**Comment by hnhhzy** [comment]
[Basic.zip](https://github.com/4as/haxe-deflatex/files/10934266/Basic.zip)

you can try this png

**Comment by hnhhzy** [comment]
`if input.readInt16()=-1895`
`var nlen:Int = input.readInt16() ^ 0xffff;`
`result is not 1894` need use UInt and ~

https://github.com/elvanaud/The_PNG_Project/blob/a05f90810f76f5cae507f06008be27a05e70dfd2/src/Deflate.cc

**Comment by hnhhzy** [comment]
input.readInt16 reads a positive integer, but Int in haxe is a signed integer, which will cause ^ 0xffff to turn out incorrectly. It has to be changed to UInt

**Comment by 4as** [comment]
I've tested your change while targeting HashLink and it also doesn't work. By the way, just so you know, doing `val ^ 0xffff` is equivalent of doing `(~val) & 0xffff`   
I checked how others are implementing this feature and for example here: https://github.com/dankogai/js-deflate/blob/master/rawinflate.js you can see the author doing the same thing I did.  
Then there is this LUA implementation: https://github.com/davidm/lua-compress-deflatelua/blob/master/lmod/compress/deflatelua.lua that simply skips the comparison and reads whatever is there in the byte stream.  
At this point I'm not sure what is wrong, but your fix doesn't change anything (at least on HashLink target). For me to approve a pull request the inflation procedure has to work on all targets.
For now I have to leave this request open, so you can propose a different fix if you want. I'll also take a look once I have more time.

**Comment by 4as** [comment]
Wait, actually, ignore my last comment. I completely forgot but you can't just plug a ZIP file into the Inflate function and expect it to work. ZIP files have special headers that need to be processed and this library doesn't support that. It only supports GZ files. You can call `GZCompressor.decompress(file)` to decompress a GZ file and it will work. Go ahead and try this again with the GZ file - if it won't work then I'll look into this. Otherwise everything works as expected. I'm closing this pull request.

**Pull request closed without merging**
